language: node_js
sudo: false
node_js: 7
cache:
  directories:
    - node_modules
before_script:
- node --version
- npm --version
script:
- npm run test-travis
- if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then npm run test-saucelabs; fi
before_deploy:
- npm install
- npm run build
- npm run dist
deploy:
  provider: npm
  email: susukang98@gmail.com
  api_key:
    secure: TYJfuTLZKbYvTskuMlmuKnQb5F35GFPN2AqSf0RtZYWGLozIaIkKcpTVbjzo859FWuxPjci53FGiJih3+0iVfIC39CDTrFZutubn8qduOfRAVTL1WzeQvdww8miJNwUY59HmoOa78OtbNCVg/N7zFSZzRXAcgje8IADQFIISwk8=
  on:
    tags: true
    branch: develop
addons:
  sauce_connect:
    username: 'summernoteis'
    access_key:
      secure: "E9Mq/lKN1xNA+PungEtlDEYqx5Dm52GPuvRMjZPkv5GiuFjof70CuqOIbqSh5YcDvn6/FmPlmlcZVNcXGzKkkSY9qqFpsbmsu2VXmbHlmpjr0Yhm7LQLoZYj+fmrO3WITai6yEyvb8cjGTjHhTjULDORJgC9U4DLfzju5OQFW0Q="
after_success:
- npm run coveralls
